import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.scss";
import coffeeStores from '../data/coffee-stores.json'

export default function Home() {
  const handleClick = () => {
    alert("hi");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleClick={handleClick} />
        <Image
          className={styles.heroImage}
          src="/static/hero-image.png"
          alt="hero-image"
          width={700}
          height={400}
        />
        <div className={styles.cardLayout}>
          {coffeeStores.map(store=>(
            <Card
            key={store.id}
              name={store.name}
              href="/coffee-store/coffee"
              imgUrl="/static/hero-image.png"
            />
          ))}
        </div>
      </main>
    </div>
  );
}
