import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const handleClick = () => {
    alert("hi");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleClick={handleClick} />
        <Image
          className={styles.heroImage}
          src="/static/hero-image.png"
          alt="hero-image"
          width={700}
          height={400}
        />
      </main>
    </div>
  );
}
